//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.customer.com/spring/soap/api/getcustomer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.customer.spring.soap.api.main;
